### PR TITLE
VB-1150-Remove-Visit-Delete-endpoint-as-this-is-not-a-requirement

### PR DESCRIPTION
**Pull request by AledWEvans**
## What does this pull request do?

removes delete visit code that has no requirement

## What is the intent behind these changes?

To reduce security risk

### CODE REVIEW

**Comment by AledWEvans** [comment]
Should I delete the service code also?

**Comment by dhirajshettymoj** [comment]
> Should I delete the java service code also?

Ideally, but as discussed we could leave it for now.

**Comment by dhirajshettymoj** [comment]
Good to merge.

**Review by dhirajshettymoj — APPROVED** [review]
Good to merge.

**Pull request merged**
