### PR TITLE
Vb 1766 delete cardiff video link visits from vsip

### PR DESCRIPTION
**Pull request by dhirajshettymoj**
## What does this pull request do?
Post data migration it was noticed that Video Link visits created on NOMIS have been migrated as part of VSIP migration. It was decided to delete these records as they need not be on VSIP.

## What is the intent behind these changes?

Data sanity.

### CODE REVIEW

**Review by rj-adams — COMMENTED** [review]
Why include the 30 minute restriction - I would have thought that we want to delete all Video link visits regardless of length

**Review by AledWEvans — APPROVED** [review]
LGTM, very nice sql ;-)

**Comment by dhirajshettymoj** [comment]
> Why include the 30 minute restriction - I would have thought that we want to delete all Video link visits regardless of length

just did a count and both return 47 records. Will update the script to remove the 30 minute constraint.

**Review by rj-adams — DISMISSED** [review]
lgtm

**Review by AledWEvans — APPROVED** [review]
LGTM

**Pull request merged**
