### PR TITLE
VB-4070 - Add public UI automation tests as step in visit-scheduler pipeline

### PR DESCRIPTION
**Pull request by adaviesMOJ**
## What does this pull request do?

Enable us to run public automation packages against the staging environment when changes are made to the underlying visit-scheduler API.

## JIRA Link
https://dsdmoj.atlassian.net/browse/VB-4070

### CODE REVIEW

**Review by dhirajshettymoj — APPROVED** [review]
LGTM

**Comment by adaviesMOJ** [comment]
Ignore PR for now - facing issues with env vars... Not ready for merging!

**Review by tpmcgowan — APPROVED** [review]
LGTM

**Review by dhirajshettymoj — APPROVED** [review]
LGTM

**Pull request merged**
